const photos = {
  home: [
    { src: "images/home/58120028.JPG", alt: "", caption: "" },
  ],

  bts: [
    { src: "images/bts/1.png", alt: "", caption: "elephantine" },
    { src: "images/bts/2.png", alt: "", caption: "elephantine" },
    { src: "images/bts/3.png", alt: "", caption: "elephantine" },
    { src: "images/bts/4.png", alt: "", caption: "elephantine" },
    { src: "images/bts/5.jpg", alt: "", caption: "elephantine" },
    { src: "images/bts/6.png", alt: "", caption: "elephantine" },
    { src: "images/bts/7.png", alt: "", caption: "elephantine" },
    { src: "images/bts/8.png", alt: "", caption: "elephantine" },
    { src: "images/bts/9.jpg", alt: "", caption: "habitat hotel" },
    { src: "images/bts/10.png", alt: "", caption: "habitat hotel" },
    { src: "images/bts/11.png", alt: "", caption: "habitat hotel" },
    { src: "images/bts/12.png", alt: "", caption: "habitat hotel" },
  ],

  events: [
    { src: "images/events/1.png", alt: "", caption: "" },
    { src: "images/events/2.jpg", alt: "", caption: "" },
    { src: "images/events/3.png", alt: "", caption: "" },
    { src: "images/events/4.png", alt: "", caption: "" },
    { src: "images/events/5.png", alt: "", caption: "" },
    { src: "images/events/6.png", alt: "", caption: "" },
    { src: "images/events/7.png", alt: "", caption: "" },
    { src: "images/events/8.png", alt: "", caption: "" },
    { src: "images/events/9.png", alt: "", caption: "" },
    { src: "images/events/10.png", alt: "", caption: "" },
    { src: "images/events/11.jpg", alt: "", caption: "" },
    { src: "images/events/12.png", alt: "", caption: "" },
    { src: "images/events/13.jpg", alt: "", caption: "" },
    { src: "images/events/14.png", alt: "", caption: "" },
    { src: "images/events/15.jpg", alt: "", caption: "" },
    { src: "images/events/16.png", alt: "", caption: "" },
    { src: "images/events/17.jpg", alt: "", caption: "" },
    { src: "images/events/18.png", alt: "", caption: "" },
    { src: "images/events/19.png", alt: "", caption: "" },
    { src: "images/events/20.png", alt: "", caption: "" },
    { src: "images/events/21.png", alt: "", caption: "" },
    { src: "images/events/22.png", alt: "", caption: "" },
    { src: "images/events/23.jpg", alt: "", caption: "" },
    { src: "images/events/24.jpg", alt: "", caption: "" },
    { src: "images/events/25.jpg", alt: "", caption: "" },
    { src: "images/events/26.jpg", alt: "", caption: "" },
    { src: "images/events/27.png", alt: "", caption: "" },
  ],

  portraits: [
    { src: "images/portraits/1.png", alt: "", caption: "" },
    { src: "images/portraits/2.png", alt: "", caption: "" },
    { src: "images/portraits/3.png", alt: "", caption: "" },
    { src: "images/portraits/4.jpg", alt: "", caption: "" },
    { src: "images/portraits/5.png", alt: "", caption: "" },
    { src: "images/portraits/6.jpg", alt: "", caption: "" },
    { src: "images/portraits/7.jpg", alt: "", caption: "" },
    { src: "images/portraits/8.jpg", alt: "", caption: "" },
    { src: "images/portraits/9.jpg", alt: "", caption: "" },
  ],

  objects: [
    { src: "images/objects/1.jpg", alt: "", caption: "" },
    { src: "images/objects/2.png", alt: "", caption: "" },
    { src: "images/objects/3.png", alt: "", caption: "" },
    { src: "images/objects/4.jpg", alt: "", caption: "" },
    { src: "images/objects/5.png", alt: "", caption: "" },
  ]
};
